[phases.setup]
nixPkgs = ["caddy", "binaryen", "rustup", "gcc", "pkg-config", "openssl", "fontconfig"]

[phases.build]
cmds = [
    "rustup default stable",
    "rustup target add wasm32-unknown-unknown",
    "curl -L https://github.com/rustwasm/wasm-bindgen/releases/download/0.2.106/wasm-bindgen-0.2.106-x86_64-unknown-linux-musl.tar.gz | tar xz",
    "cargo build --release --target wasm32-unknown-unknown",
    "./wasm-bindgen-0.2.106-x86_64-unknown-linux-musl/wasm-bindgen --out-dir ./out --target web ./target/wasm32-unknown-unknown/release/farm-blazer.wasm",
    "wasm-opt -Oz -o ./out/farm-blazer_bg.wasm ./out/farm-blazer_bg.wasm",
    "mv ./out/farm-blazer.js ./out/farm-blazer.js",
    "rm ./out/farm-blazer_bg.wasm"
]

[start]
cmd = "caddy file-server --root ./out --listen :80"
