[phases.setup]
nixPkgs = ["caddy", "binaryen"]
aptPkgs = ["gcc"]

[phases.build]
cmds = [
    "cargo install -f wasm-bindgen-cli --version 0.2.106",
    "cargo build --release --target wasm32-unknown-unknown",
    "wasm-bindgen --out-dir ./out --target web ./target/wasm32-unknown-unknown/release/farm_blazer.wasm",
    "wasm-opt -Oz -o ./out/farm-blazer_bg.wasm ./out/farm_blazer_bg.wasm",
    "mv ./out/farm_blazer.js ./out/farm-blazer.js",
    "rm ./out/farm_blazer_bg.wasm"
]

[start]
cmd = "caddy file-server --root ./out --listen :80"
